name: Run Trading Bot Continuous

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-bot-loop:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install ccxt pandas numpy requests

      - name: Run Bot
        run: python bot.py
